package com.example.nutrilens.domain.service

import com.example.nutrilens.domain.model.NutritionInfo

class NutritionEngine {

    private val foodDatabase: Map<String, NutritionInfo> = mapOf(
        "apple" to NutritionInfo(52, 10.4),
        "banana" to NutritionInfo(89, 12.2),
        "orange" to NutritionInfo(47, 9.4),
        "grape" to NutritionInfo(69, 15.5),
        "strawberry" to NutritionInfo(32, 4.9),
        "blueberry" to NutritionInfo(57, 10.0),
        "watermelon" to NutritionInfo(30, 6.2),
        "pineapple" to NutritionInfo(50, 9.9),
        "mango" to NutritionInfo(60, 13.7),
        "peach" to NutritionInfo(39, 8.4),
        "pear" to NutritionInfo(57, 9.8),
        "cherry" to NutritionInfo(50, 8.0),
        "kiwi" to NutritionInfo(61, 9.0),
        "lemon" to NutritionInfo(29, 2.5),
        "lime" to NutritionInfo(30, 1.7),
        "avocado" to NutritionInfo(160, 0.7),
        "tomato" to NutritionInfo(18, 2.6),
        "cucumber" to NutritionInfo(15, 2.0),
        "carrot" to NutritionInfo(41, 4.7),
        "broccoli" to NutritionInfo(34, 1.7),
        "cauliflower" to NutritionInfo(25, 1.9),
        "spinach" to NutritionInfo(23, 0.4),
        "lettuce" to NutritionInfo(15, 0.8),
        "kale" to NutritionInfo(49, 0.9),
        "cabbage" to NutritionInfo(25, 3.2),
        "potato" to NutritionInfo(77, 0.8),
        "sweet potato" to NutritionInfo(86, 4.2),
        "onion" to NutritionInfo(40, 4.2),
        "garlic" to NutritionInfo(149, 1.0),
        "bell pepper" to NutritionInfo(31, 2.4),
        "celery" to NutritionInfo(16, 1.4),
        "zucchini" to NutritionInfo(17, 1.1),
        "eggplant" to NutritionInfo(25, 3.5),
        "mushroom" to NutritionInfo(22, 1.7),
        "corn" to NutritionInfo(96, 3.2),
        "peas" to NutritionInfo(81, 5.7),
        "green bean" to NutritionInfo(31, 1.4),
        "rice" to NutritionInfo(130, 0.1),
        "white rice" to NutritionInfo(130, 0.1),
        "brown rice" to NutritionInfo(111, 0.4),
        "pasta" to NutritionInfo(131, 0.6),
        "spaghetti" to NutritionInfo(131, 0.6),
        "bread" to NutritionInfo(265, 5.0),
        "white bread" to NutritionInfo(265, 5.0),
        "whole wheat bread" to NutritionInfo(247, 3.4),
        "oatmeal" to NutritionInfo(71, 0.3),
        "cereal" to NutritionInfo(112, 1.8),
        "granola" to NutritionInfo(471, 19.8),
        "pancake" to NutritionInfo(227, 5.5),
        "waffle" to NutritionInfo(291, 8.7),
        "chicken" to NutritionInfo(165, 0.0),
        "chicken breast" to NutritionInfo(165, 0.0),
        "chicken thigh" to NutritionInfo(209, 0.0),
        "beef" to NutritionInfo(250, 0.0),
        "steak" to NutritionInfo(271, 0.0),
        "pork" to NutritionInfo(242, 0.0),
        "lamb" to NutritionInfo(294, 0.0),
        "fish" to NutritionInfo(206, 0.0),
        "salmon" to NutritionInfo(208, 0.0),
        "tuna" to NutritionInfo(132, 0.0),
        "shrimp" to NutritionInfo(99, 0.0),
        "egg" to NutritionInfo(155, 0.6),
        "eggs" to NutritionInfo(155, 0.6),
        "milk" to NutritionInfo(42, 4.9),
        "whole milk" to NutritionInfo(61, 5.2),
        "skim milk" to NutritionInfo(34, 4.9),
        "cheese" to NutritionInfo(402, 0.5),
        "cheddar" to NutritionInfo(402, 0.5),
        "mozzarella" to NutritionInfo(280, 1.0),
        "yogurt" to NutritionInfo(61, 4.7),
        "greek yogurt" to NutritionInfo(59, 3.0),
        "butter" to NutritionInfo(717, 0.1),
        "cream" to NutritionInfo(345, 2.8),
        "ice cream" to NutritionInfo(207, 19.0),
        "chocolate" to NutritionInfo(546, 44.0),
        "dark chocolate" to NutritionInfo(546, 24.0),
        "milk chocolate" to NutritionInfo(535, 51.0),
        "cookie" to NutritionInfo(488, 30.0),
        "cake" to NutritionInfo(352, 30.0),
        "donut" to NutritionInfo(452, 22.0),
        "muffin" to NutritionInfo(424, 29.0),
        "pie" to NutritionInfo(237, 12.0),
        "pizza" to NutritionInfo(266, 3.5),
        "burger" to NutritionInfo(297, 5.0),
        "hamburger" to NutritionInfo(297, 5.0),
        "cheeseburger" to NutritionInfo(309, 5.0),
        "hot dog" to NutritionInfo(290, 5.0),
        "sandwich" to NutritionInfo(250, 4.0),
        "soup" to NutritionInfo(50, 2.0),
        "salad" to NutritionInfo(30, 1.5),
        "fries" to NutritionInfo(312, 0.3),
        "french fries" to NutritionInfo(312, 0.3),
        "chips" to NutritionInfo(536, 0.2),
        "potato chips" to NutritionInfo(536, 0.2),
        "noodles" to NutritionInfo(138, 0.5),
        "ramen" to NutritionInfo(138, 0.5),
        "sushi" to NutritionInfo(130, 2.0),
        "tofu" to NutritionInfo(76, 0.7),
        "tempeh" to NutritionInfo(193, 0.0),
        "almond" to NutritionInfo(579, 4.4),
        "walnut" to NutritionInfo(654, 2.6),
        "cashew" to NutritionInfo(553, 5.0),
        "peanut" to NutritionInfo(567, 3.5),
        "peanut butter" to NutritionInfo(588, 10.0),
        "almond butter" to NutritionInfo(614, 4.4),
        "hummus" to NutritionInfo(166, 0.5),
        "olive oil" to NutritionInfo(884, 0.0),
        "canola oil" to NutritionInfo(884, 0.0),
        "sugar" to NutritionInfo(387, 99.9),
        "honey" to NutritionInfo(304, 82.1),
        "maple syrup" to NutritionInfo(260, 60.5),
        "ketchup" to NutritionInfo(101, 21.3),
        "mustard" to NutritionInfo(66, 3.0),
        "mayonnaise" to NutritionInfo(717, 0.6),
        "vinegar" to NutritionInfo(18, 0.4),
        "soy sauce" to NutritionInfo(53, 4.4),
        "soda" to NutritionInfo(41, 10.2),
        "cola" to NutritionInfo(41, 10.6),
        "orange juice" to NutritionInfo(45, 8.4),
        "apple juice" to NutritionInfo(46, 10.1),
        "coffee" to NutritionInfo(1, 0.0),
        "tea" to NutritionInfo(1, 0.0),
        "beer" to NutritionInfo(43, 0.0),
        "wine" to NutritionInfo(83, 0.6),
        "water" to NutritionInfo(0, 0.0),
        "rice cake" to NutritionInfo(386, 0.3),
        "popcorn" to NutritionInfo(387, 0.9),
        "pretzel" to NutritionInfo(380, 2.2),
        "cracker" to NutritionInfo(480, 5.0),
        "bacon" to NutritionInfo(541, 0.0),
        "sausage" to NutritionInfo(299, 1.0),
        "ham" to NutritionInfo(145, 0.5),
        "turkey" to NutritionInfo(189, 0.0),
        "duck" to NutritionInfo(337, 0.0),
        "lobster" to NutritionInfo(89, 0.0),
        "crab" to NutritionInfo(87, 0.0),
        "clam" to NutritionInfo(74, 0.0),
        "mango sticky rice" to NutritionInfo(170, 15.0),
        "fried rice" to NutritionInfo(179, 0.4),
        "curry" to NutritionInfo(200, 3.0),
        "taco" to NutritionInfo(226, 2.0),
        "burrito" to NutritionInfo(250, 3.0),
        "quesadilla" to NutritionInfo(294, 3.0),
        "nachos" to NutritionInfo(306, 4.0),
        "guacamole" to NutritionInfo(160, 0.7),
        "salsa" to NutritionInfo(20, 2.0),
        "rice pudding" to NutritionInfo(134, 13.0),
        "pudding" to NutritionInfo(155, 14.0),
        "custard" to NutritionInfo(130, 10.0),
        "cheesecake" to NutritionInfo(321, 22.0),
        "brownie" to NutritionInfo(466, 35.0),
        "cupcake" to NutritionInfo(305, 25.0),
        "ice cream sandwich" to NutritionInfo(250, 20.0),
        "oatmeal cookie" to NutritionInfo(450, 24.0),
        "chocolate chip cookie" to NutritionInfo(488, 31.0),
        "smoothie" to NutritionInfo(100, 15.0),
        "protein shake" to NutritionInfo(150, 3.0),
        "energy bar" to NutritionInfo(250, 15.0),
        "granola bar" to NutritionInfo(200, 10.0),
        "candy bar" to NutritionInfo(450, 40.0),
        "gummy" to NutritionInfo(350, 40.0),
        "licorice" to NutritionInfo(350, 50.0),
        "croissant" to NutritionInfo(406, 11.0),
        "bagel" to NutritionInfo(250, 4.5),
        "english muffin" to NutritionInfo(235, 3.0),
        "tortilla" to NutritionInfo(200, 1.0),
        "naan" to NutritionInfo(262, 3.0),
        "pita" to NutritionInfo(275, 1.0),
        "tortilla chip" to NutritionInfo(490, 2.0),
        "pita chip" to NutritionInfo(457, 3.0),
        "bagel chip" to NutritionInfo(450, 4.0),
        "stuffing" to NutritionInfo(180, 2.0),
        "mashed potato" to NutritionInfo(90, 1.0),
        "baked potato" to NutritionInfo(93, 1.0),
        "roasted potato" to NutritionInfo(150, 0.5),
        "potato salad" to NutritionInfo(160, 2.0),
        "coleslaw" to NutritionInfo(75, 5.0),
        "caesar salad" to NutritionInfo(150, 2.0),
        "greek salad" to NutritionInfo(100, 2.0),
        "fruit salad" to NutritionInfo(80, 12.0),
        "grilled cheese" to NutritionInfo(350, 4.0),
        "chicken salad" to NutritionInfo(200, 3.0),
        "egg salad" to NutritionInfo(220, 2.0),
        "tuna salad" to NutritionInfo(190, 1.0),
        "pasta salad" to NutritionInfo(200, 2.0),
        "macaroni and cheese" to NutritionInfo(180, 5.0),
        "mac and cheese" to NutritionInfo(180, 5.0),
        "lasagna" to NutritionInfo(135, 4.0),
        "ravioli" to NutritionInfo(130, 3.0),
        "gnocchi" to NutritionInfo(130, 0.5),
        "risotto" to NutritionInfo(130, 0.5),
        "paella" to NutritionInfo(160, 1.0),
        "stir fry" to NutritionInfo(120, 3.0),
        "chow mein" to NutritionInfo(180, 3.0),
        "lo mein" to NutritionInfo(180, 3.0),
        "dumpling" to NutritionInfo(150, 1.0),
        "spring roll" to NutritionInfo(100, 3.0),
        "egg roll" to NutritionInfo(180, 4.0),
        "dim sum" to NutritionInfo(150, 2.0),
        "falafel" to NutritionInfo(333, 3.0),
        "kebab" to NutritionInfo(200, 2.0),
        "shawarma" to NutritionInfo(250, 3.0),
        "gyro" to NutritionInfo(250, 3.0),
        "hummus plate" to NutritionInfo(200, 1.0),
        "baba ganoush" to NutritionInfo(75, 2.0),
        "tabbouleh" to NutritionInfo(180, 3.0),
        "couscous" to NutritionInfo(112, 0.2),
        "quinoa" to NutritionInfo(120, 0.9),
        "lentil" to NutritionInfo(116, 1.8),
        "lentil soup" to NutritionInfo(80, 1.5),
        "bean soup" to NutritionInfo(100, 2.0),
        "chicken soup" to NutritionInfo(50, 1.0),
        "tomato soup" to NutritionInfo(70, 8.0),
        "mushroom soup" to NutritionInfo(85, 2.5),
        "minestrone" to NutritionInfo(60, 3.0),
        "clam chowder" to NutritionInfo(100, 2.0),
        "broccoli cheddar soup" to NutritionInfo(120, 4.0),
        "pumpkin soup" to NutritionInfo(60, 4.0),
        "carrot soup" to NutritionInfo(60, 6.0),
        "gazpacho" to NutritionInfo(30, 3.0),
        "pho" to NutritionInfo(200, 3.0),
        "ramen soup" to NutritionInfo(300, 2.0),
        "udon" to NutritionInfo(140, 2.0),
        "soba" to NutritionInfo(130, 1.0)
    )

    fun has(foodName: String): Boolean {
        val normalized = foodName.trim().lowercase()
        if (foodDatabase.containsKey(normalized)) return true
        for (key in foodDatabase.keys) {
            if (normalized.contains(key) || key.contains(normalized)) return true
        }
        val words = normalized.split(" ")
        for (key in foodDatabase.keys) {
            for (word in words) {
                if (word == key || key.contains(word) && word.length > 2) return true
            }
        }
        return false
    }

    fun estimate(foodName: String): NutritionInfo {
        val normalized = foodName.trim().lowercase()

        foodDatabase[normalized]?.let { return it }

        for ((key, info) in foodDatabase) {
            if (normalized.contains(key) || key.contains(normalized)) {
                return info
            }
        }

        val words = normalized.split(" ")
        for ((key, info) in foodDatabase) {
            for (word in words) {
                if (word == key || key.contains(word) && word.length > 2) {
                    return info
                }
            }
        }

        return NutritionInfo(100, 5.0)
    }
}
